events { worker_connections 1024; }

http {
    server {
        listen 80;

        # Rediriger vers Keycloak
        location /auth/ {
            proxy_pass http://hp_keycloak:8080/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Rediriger vers Grafana
        location /monitor/ {
            proxy_pass http://hp_grafana:3000/;
            proxy_set_header Host $host;
        }
        
        # Racine de l'API (pour Amal plus tard)
        location /api/ {
            proxy_pass http://auth-service:3000/;
        }
    }
}